# Generated by Django 5.1 on 2025-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dockercontainer_container_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('docker', 'Docker'), ('k8s', 'Kubernetes')], max_length=50)),
                ('container_id', models.CharField(max_length=255)),
                ('container_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('error_message', models.TextField()),
                ('short_message', models.CharField(blank=True, max_length=1024, null=True)),
                ('level', models.CharField(choices=[('Error', 'Error'), ('Warning', 'Warning')], default='Error', max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка контейнера',
                'verbose_name_plural': 'Ошибки контейнеров',
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['source_type', 'container_id'], name='main_contai_source__64b2c3_idx'), models.Index(fields=['container_name'], name='main_contai_contain_e38db7_idx'), models.Index(fields=['level'], name='main_contai_level_37c874_idx'), models.Index(fields=['-timestamp'], name='main_contai_timesta_c567cc_idx')],
            },
        ),
    ]
